### ISSUE TITLE
No need for HEV to see HUD?

### ISSUE THREAD

**Issue by sabianroberts** [SamVanheer/halflife-bs-updated#1]
If I'm correct, there is still an `item_suit` entity in the `info_player_start,` so Calhoun still has a HEV suit. It would probably be best to remove the HEV requirement, as it's
- not canon that Barney needs his armour for the HUD
- easier for the player to skip maps

A simple modification that won't harm playability.

**Comment by SamVanheer** [comment]
I wouldn't call that a simple modification. There are checks for the HEV suit all over the place, and if you're skipping maps you can easily give yourself the suit with `give item_suit`.

Keeping it as it is keeps the behavior consistent with all Half-Life games, and if mappers want to make a map where you don't have the HUD at any point (like Half-Life's Inbound and Anomalous Materials chapters) then they can do this easily by not giving the suit. 

There is currently no way to strip the suit from the player (`player_weaponstrip` only removes weapons) but that can be added easily enough.
