### ISSUE TITLE
Health does not regenerate after holding your breath

### ISSUE THREAD

**Issue by Ronin4862** [SamVanheer/halflife-bs-updated#10]
https://youtu.be/4Qiu96Typ3c

**Comment by Ronin4862** [comment]
I see you fixed it literally a few hours before I reported this.
But what caused this bug?
It was never present before.

**Comment by SamVanheer** [comment]
You can see which changes were made using git blame: https://github.com/SamVanheer/halflife-updated/blame/7fbccedbd9d2adc115f8f6e61dcd58858c0f5b3c/dlls/player.cpp#L1112
