### ISSUE TITLE
Scientist heals the player with the wrong hand

### ISSUE THREAD

**Issue by Ronin4862** [SamVanheer/halflife-bs-updated#5]
https://youtu.be/LscAyMM4tjM

**Comment by SamVanheer** [comment]
Looks like the LD model is using the HD animation. I'll see if i can switch it out.

**Comment by SamVanheer** [comment]
The Unified SDK has a fixed version of this model, but since we also separated Rosenberg into its own model we can't use it here. You'll be able to play Blue Shift through that just fine so there's no need to fix it here, since it's such a minor issue.
