### ISSUE TITLE
Alien Aircraft still heard after loading a game

### ISSUE THREAD

**Issue by Ronin4862** [SamVanheer/halflife-bs-updated#6]
https://youtu.be/aQPCab1iYs0

Probably a map scripting bug.

If so, you can send it to Hezus (if he ever plans to release a BS: Enriched).

The map is Focal Point.

**Comment by Ronin4862** [comment]
I didn't want to start a new issue.
The same happens in Half-Life on Xen in the map with the tentacles and a Gargantua after loading a saved game.
Also, after killing Gonarch in its lair. Loading a saved game causes the death moan to be replayed.

**Comment by Ronin4862** [comment]
Also, in Interloper you can hear Nihilanth's taunts again after loading a saved game.

**Comment by SamVanheer** [comment]
I've created a new issue to track these problems: https://github.com/SamVanheer/halflife-unified-sdk/issues/452
